# Generated by Django 5.0 on 2024-08-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddVehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(max_length=200)),
                ('parking_area_no', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=200)),
                ('parking_charge', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('arrival_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('parking_area_no', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_limit', models.CharField(max_length=200)),
                ('parking_charge', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('doc', models.DateTimeField()),
            ],
        ),
    ]
